name: Lint

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  configs:
    uses: LouisBrunner/.github/.github/workflows/lint-configs.yml@main
    with:
      run-biome: false

  brew:
    name: brew style
    runs-on: macos-15
    steps:
      - uses: ./.github/actions/setup

      - run: brew audit local/valgrind/valgrind
      - run: brew style local/valgrind/valgrind
