# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  lint:
    uses: LouisBrunner/.github/.github/workflows/lint-all.yml@main
    permissions:
      actions: read
      contents: read
      statuses: write
      pull-requests: write

  brew:
    name: brew style
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: ./.github/actions/setup

      - run: brew audit --except-cops miscellaneous local/valgrind/valgrind
      - run: brew style --except-cops miscellaneous local/valgrind/valgrind
