name: Test

on:
  push:
  pull_request_target:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_various_platforms:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14, macos-15, macos-15-intel, macos-26]

    runs-on: ${{ matrix.os }}

    name: Test on ${{matrix.os}}

    steps:
      - uses: ./.github/actions/setup

      - name: install formula locally
        run: brew install --HEAD local/valgrind/valgrind
        env:
          # FIXME: needed for macos-15 (for now)
          HOMEBREW_I_ACKNOWLEDGE_THIS_MIGHT_CRASH_OR_DAMAGE_MY_COMPUTER: yes
      - name: upgrade formula locally
        run: brew upgrade --fetch-HEAD local/valgrind/valgrind
        env:
          # FIXME: needed for macos-15 (for now)
          HOMEBREW_I_ACKNOWLEDGE_THIS_MIGHT_CRASH_OR_DAMAGE_MY_COMPUTER: yes
